### ISSUE TITLE
Use intermediate to advance Java concepts to print "Hello, World!"

### ISSUE THREAD

**Issue by NachiketaVadera** [NachiketaVadera/100-ways-to-print-HelloWorld-in-java#35]
# Task

- [X] The output of your program should be "Hello, World!"
- [X] Make sure you check out some of the programs in the repository to get the idea.
- [x] Use an intermediate or advance topic in Java to output "Hello, World!"
- [x] Make sure that you don't submit a duplicate of an already existing program.

**Comment by apol657** [comment]
I would like to do this with some Reflection nonsense :)
